#!/usr/bin/env python3


from datetime import datetime as dt
from datetime import timedelta as delta


def total_today():
    count = 0

    now = dt.now()
    now = now.strftime("%d %m %Y")
    day, month, year = now.split()
    for _ in log:
        _ = int(_)
        _ = dt.fromtimestamp(_)
        _ = _.strftime("%d %m %Y")
        _day, _month, _year = _.split()

        rules = [ 
            day   == _day, 
            month == _month, 
            year  == _year 
        ]

        if all(rules):
            count += 1

    return count


def most_recent():
    if not log:
        return -1
    length = len(log)
    recent = log[length - 1]
    recent = int(recent)

    # last entry in log converted to <datetime>
    recent = dt.fromtimestamp(recent)
    now    = dt.now()

    # calculates time between current time and last entry
    # in log
    delta  = now - recent

    return delta.total_seconds()


def relapse():
    user_input = input("Have you relapsed [y/n]: ")

    if user_input[0].lower() == 'y':
        cur_time   = dt.now()
        unix       = dt.timestamp(cur_time)
        unix       = int(unix)

        log.append(str(unix))
        write_to_file(unix)

    for i, time in enumerate(log, start=1):
        time = dt.fromtimestamp(int(time))
        difference = dt.now() - time
        #print(i+1, time.strftime("%D %H:%M"), difference, sep=" ┃ ")
        print(f"{i:>3}┃ {time.strftime('%D %H:%M')} ┃ {difference}")

    

def write_to_file(message):
    with open(file_path, "a") as file:
        file.write(f"{message}\n")


def retrieve_from_file():
    try:
        # read unix timestamps from file
        with open(file_path, "r") as file:
            file_contents = [timestamp.replace('\n', '') for
                timestamp in file if timestamp != ""]

    # create file incase it is not found
    except FileNotFoundError:
        with open(file_path, "w") as file:
            file.write("")
        file_contents = []

    return file_contents
        

if __name__ == "__main__":
    file_path = "log.txt"
    log       = retrieve_from_file()

    relapse()

    since_last = int(most_recent())
    since_last = str(delta(seconds=since_last))
    print(f"Seconds since last relapse: {since_last}")
    print(f"Times relapsed today      : {total_today()}")

